---
- name: create minio directory
  file:
    path: "/home/{{ ansible_user }}/minio/data"
    state: directory
    recurse: yes

- name: check file minio
  stat:
    path: /usr/local/bin/minio
  register: minio

# 最新ビルドのダウンロードリンクしか公開されていないため
# 同じバイナリでも毎回ダウンロードしてしまう
# そのため既存バイナリがあるときはスキップする
- name: setup minio
  block:
  - name: download minio server
    get_url:
      url: https://dl.min.io/server/minio/release/linux-amd64/minio
      dest: /usr/local/bin/minio
      mode: '0755'
  - name: download minio client
    get_url:
      url: https://dl.min.io/client/mc/release/linux-amd64/mc
      dest: /usr/local/bin/mc
      mode: '0755'
  become: yes
  when: not minio.stat.exists

- name: setup supervisor for minio
  block:
  - name: install supervisor
    apt:
      name: supervisor
      update_cache: yes
      cache_valid_time: 3600
  - name: add minio.conf to supervisor
    template:
      src: ./templates/minio.conf.j2
      dest: /etc/supervisor/conf.d/minio.conf
  - name: Restart supervisord
    supervisorctl:
      name: minio
      state: restarted
  become: yes
